language: go
go:
    1.7.x
install:
  - go get -v github.com/Masterminds/glide
  - go get golang.org/x/net/context
  - go get golang.org/x/net/context/ctxhttp
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
  - glide install
  - cd $GOPATH/src/github.com/mattmac4241/chat-auth
script:
 - go test -v $GOPATH/src/github.com/mattmac4241/chat-auth/...
